### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by loretoparisi** [Danangjoyoo/flask-http-middleware#10]
When used as a middlware into Superset Flask app I get

```bash
superset_app           | TypeError: __init__() takes 1 positional argument but 2 were given
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 897, in run_command
superset_app           |     app = info.load_app()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 308, in load_app
superset_app           |     app = locate_app(import_name, name)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 237, in locate_app
superset_app           |     return find_app_by_string(module, app_name)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 165, in find_app_by_string
superset_app           |     app = attr(*args, **kwargs)
superset_app           |   File "/app/superset/app.py", line 47, in create_app
superset_app           |     raise ex
superset_app           |   File "/app/superset/app.py", line 40, in create_app
superset_app           |     app_initializer.init_app()
superset_app           |   File "/app/superset/initialization/__init__.py", line 485, in init_app
superset_app           |     self.configure_middlewares()
superset_app           |   File "/app/superset/initialization/__init__.py", line 588, in configure_middlewares
superset_app           |     self.superset_app.wsgi_app = middleware(self.superset_app.wsgi_app)
superset_app           | TypeError: __init__() takes 1 positional argument but 2 were given
```

where the middleware was integrated using the `ADDITIONAL_MIDDLEWARE` (docs [here](https://superset.apache.org/docs/installation/networking-settings/))

```python
class MetricsMiddleware(BaseHTTPMiddleware):
    def __init__(self):
        super().__init__()

    def dispatch(self, request, call_next):
        t0 = time.time()
        response = call_next(request)
        response_time = time.time()-t0
        response.headers.add("response_time", response_time)
        return response
    
ADDITIONAL_MIDDLEWARE = [MetricsMiddleware, ]
```

If I look at the example provided

```python
app.wsgi_app = MiddlewareManager(app)
app.wsgi_app.add_middleware(MetricsMiddleware)
```

and to the error in the stacktrace:

```bash
superset_app           |   File "/app/superset/initialization/__init__.py", line 588, in configure_middlewares
superset_app           |     self.superset_app.wsgi_app = middleware(self.superset_app.wsgi_app)
```

it seems the problem is the `MiddlewareManager` override. Is it possible to bypass it?

**Comment by loretoparisi** [comment]
So I was able to fix that, importing the Superset wsig app and following your example:

```python
from superset.app import SupersetAppInitializer
def app_init(app):
    logging.info("Registering middlewares")
    app.wsgi_app = MiddlewareManager(app)
    app.wsgi_app.add_middleware(MetricsMiddleware)
    return SupersetAppInitializer(app)
APP_INITIALIZER = app_init
```

🔝
