### ISSUE TITLE
Error when running the example code

### ISSUE THREAD

**Issue by zenr** [Danangjoyoo/flask-http-middleware#2]
I am using 

Python 3.7.4
Flask 2.2.2
Werkzeug 2.2.2

and when I run the example code supplied with this repo, I am getting the following error

```
[2022-12-27 20:20:15,963] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/chityala/opt/anaconda3/lib/python3.7/site-packages/flask_http_middleware/manager.py", line 46, in __call__
    self.app.try_trigger_before_first_request_functions()
AttributeError: 'Flask' object has no attribute 'try_trigger_before_first_request_functions'
127.0.0.1 - - [27/Dec/2022 20:20:15] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/chityala/opt/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/Users/chityala/opt/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/Users/chityala/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/chityala/opt/anaconda3/lib/python3.7/site-packages/flask_http_middleware/manager.py", line 71, in __call__
    ctx.auto_pop(error)
AttributeError: 'RequestContext' object has no attribute 'auto_pop'
```

Any suggestions on how I can fix it?

**Comment by Danangjoyoo** [comment]
Hi @zenr , thanks for the notice.

I found out that a newer `flask` version is not supported yet (I've been testing this on `flask==2.1.2` and works fine but found the same error as yours on `flask==2.2.2`)

perhaps you could use the lower version of flask (I suggest `flask==2.1.2`) until the new version of this package is released

**Comment by Danangjoyoo** [comment]
I already update this package it would be works now on your case. You don't have to change your `flask` version. Just install the newer version of `flask-http-middleware`

```
pip install --upgrade flask-http-middleware
```

**Comment by Danangjoyoo** [comment]
@zenr have you test it?

**Comment by Danangjoyoo** [comment]
will close this issue as its been solved
