### ISSUE TITLE
Issue with Flask 2.3

### ISSUE THREAD

**Issue by mariofix** [Danangjoyoo/flask-http-middleware#5]
Hi! I have a problem when using Flask 2.3.x 
I get this error when loading any page

```
Traceback (most recent call last):
  File "/home/mariofix/.cache/pypoetry/virtualenvs/firenze-XTdKpJkd-py3.11/lib/python3.11/site-packages/flask_http_middleware/manager.py", line 113, in __call__
    response = self.app.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mariofix/.cache/pypoetry/virtualenvs/firenze-XTdKpJkd-py3.11/lib/python3.11/site-packages/flask_http_middleware/manager.py", line 96, in __call__
    self.app.try_trigger_before_first_request_functions()
AttributeError: 'Flask' object has no attribute 'try_trigger_before_first_request_functions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mariofix/.cache/pypoetry/virtualenvs/firenze-XTdKpJkd-py3.11/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mariofix/.cache/pypoetry/virtualenvs/firenze-XTdKpJkd-py3.11/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mariofix/.cache/pypoetry/virtualenvs/firenze-XTdKpJkd-py3.11/lib/python3.11/site-packages/flask_http_middleware/manager.py", line 121, in __call__
    ctx.auto_pop(error)
AttributeError: 'RequestContext' object has no attribute 'auto_pop'
```

I can also confirm the error disappears when downgrading to flask 2.2.5

**Comment by Danangjoyoo** [comment]
Hi thanks for reporting, I'll be checking this compatibility issue soon

**Comment by Danangjoyoo** [comment]
Hi this issue already fixed, please update your `flask-http-middleware` to the newest
